"""Build the reference-derived voice from a decoded mono float32 recording.

Requires numpy. Decode the supplied performance at 22050 Hz before running.
Usage: python scripts/build-reference-bank.py path/to/reference.f32
Only selected, frequency-isolated attacks are retained. Overlapping tails are
replaced with fitted decaying modes; this is not an exact acoustic separation.
"""
import base64
import json
import sys
from pathlib import Path
import numpy as np

SR = 22050
# Selected strikes and their observed, non-harmonic resonances in the reference.
STRIKES = [
    (194, 27.9104, [194, 393, 910, 1927, 2390]),
    (216, 46.7302, [216, 441, 883, 2153]),
    (247, 56.9469, [247, 495, 1136, 2315]),
    (264, 32.1016, [264, 532, 1227, 2578, 3235]),
    (296, 34.5049, [296, 592, 1367, 2988, 3505, 3774]),
    (329, 37.9530, [329, 668, 1475, 1572, 3693]),
    (350, 30.3717, [350, 705, 1604, 1647, 4231]),
    (705, 22.5234, [705, 1416, 3112]),
]

def analytic_band(spectrum, frequencies, center, width):
    mask = np.exp(-.5 * ((frequencies - center) / width) ** 4)
    return np.fft.ifft(spectrum * mask * 2)

def pcm(values):
    return base64.b64encode((np.clip(values, -1, 1) * 32767).astype('<i2').tobytes()).decode('ascii')

def build(raw):
    result = []
    for root, strike, centers in STRIKES:
        start = int((strike - .3) * SR)
        segment = raw[start:start + int(1.3 * SR)].astype(float)
        n = 2 ** int(np.ceil(np.log2(len(segment) * 2)))
        spectrum = np.fft.fft(segment * np.hanning(len(segment)), n)
        frequencies = np.fft.fftfreq(n, 1 / SR)
        fundamental = analytic_band(spectrum, frequencies, root, 9)
        envelope = np.abs(fundamental)
        derivative = envelope[int(.015 * SR):] - envelope[:-int(.015 * SR)]
        lo, hi = int(.25 * SR), int(.48 * SR)
        onset = lo + np.argmax(derivative[lo:hi])
        count = int(3.6 * SR)
        t = np.arange(count) / SR
        voice = np.zeros(count)
        measurements = []
        actual_root = root
        for index, center in enumerate(centers):
            band = analytic_band(spectrum, frequencies, center, 9 if center < 800 else 15)
            sample = band[onset:onset + int(.32 * SR)]
            local_t = np.arange(len(sample)) / SR
            fit = (local_t > .075) & (local_t < .2)
            amp = np.abs(sample)
            phase = np.unwrap(np.angle(sample))
            slope, phase0 = np.polyfit(local_t[fit], phase[fit], 1)
            hz = slope / (2 * np.pi)
            if abs(hz - center) > 18: hz = center; phase0 = np.median(phase[fit] - 2 * np.pi * hz * local_t[fit])
            if index == 0: actual_root = hz
            log_slope, log_amp = np.polyfit(local_t[fit], np.log(np.maximum(amp[fit], 1e-7)), 1)
            # Bound estimates when another strike or room noise contaminates decay.
            tau = float(np.clip(-1 / min(log_slope, -.5), .18 if index else .38, .7 if index else 1.1))
            at_join = np.median(amp[fit] * np.exp(local_t[fit] / tau))
            tail = at_join * np.exp(-t / tau) * np.cos(2 * np.pi * hz * t + phase0)
            crossfade = np.clip((local_t - .16) / .10, 0, 1)
            tail[:len(sample)] = sample.real * (1 - crossfade) + tail[:len(sample)] * crossfade
            voice += tail
            measurements.append({'hz': round(hz, 3), 'decaySeconds': round(tau, 3)})
        voice *= np.minimum(1, t / .004)
        voice *= np.clip((3.6 - t) / .1, 0, 1)
        voice *= .68 / max(np.max(np.abs(voice)), 1e-6)
        # Keep a short, high-frequency contact texture, not the ongoing performance.
        attack_start = start + onset
        attack = raw[attack_start:attack_start + int(.055 * SR)].astype(float)
        a_freq = np.fft.rfftfreq(len(attack), 1 / SR)
        a_spec = np.fft.rfft(attack)
        a_spec *= np.clip((a_freq - 1800) / 1600, 0, 1)
        attack = np.fft.irfft(a_spec, n=len(attack))
        attack *= np.exp(-np.arange(len(attack)) / (SR * .012))
        attack *= np.minimum(1, np.arange(len(attack)) / (SR * .001))
        attack *= .5 / max(np.max(np.abs(attack)), 1e-6)
        result.append({'rootHz': round(float(actual_root), 4), 'sourceSeconds': round(strike, 4), 'modes': measurements, 'pcm': pcm(voice), 'attack': pcm(attack)})
        print('Reference strike:', root, 'Hz ->', round(actual_root, 2), 'Hz;', measurements)
    return {'sampleRate': SR, 'description': 'Frequency-isolated reference attacks with fitted modal tails; not isolated studio samples.', 'samples': result}

if __name__ == '__main__':
    bank = build(np.fromfile(sys.argv[1], dtype='<f4'))
    target = Path(__file__).resolve().parents[1] / 'reference-bank.js'
    target.write_text('// Generated by scripts/build-reference-bank.py from the supplied performance.\n'
                      '// Includes short filtered attacks and reconstructed decay, not the video.\n'
                      'globalThis.MbiraReference = ' + json.dumps(bank, separators=(',', ':')) + ';\n', encoding='utf-8')
    print('Wrote', target.name, target.stat().st_size, 'bytes')
