"""Build Nyunga Nyunga timbre from the owner's 48-second video (22050 Hz mono float32)."""
import importlib.util
import json
import sys
from pathlib import Path
import numpy as np
spec = importlib.util.spec_from_file_location('reference_builder', Path(__file__).with_name('build-reference-bank.py'))
builder = importlib.util.module_from_spec(spec)
spec.loader.exec_module(builder)
# Measured fundamentals and metallic modes from separate strikes in this video.
builder.STRIKES = [
    (226, 3.106, [226, 452, 1157, 3004]),
    (264, 6.598, [264, 506, 1297]),
    (301, 10.130, [301, 598, 1475]),
    (350, 8.594, [350, 700, 1647]),
    (404, 16.655, [404, 808, 1852]),
    (447, 13.283, [447, 894, 2051]),
]
bank = builder.build(np.fromfile(sys.argv[1], dtype='<f4'))
bank['description'] = 'Nyunga Nyunga video-derived strikes with filtered attacks and fitted decay. Transposed to the supplied key mapping.'
target = Path(__file__).resolve().parents[1] / 'nyunga-bank.js'
target.write_text('// Generated by scripts/build-nyunga-bank.py from the owner-supplied Nyunga Nyunga video.\nglobalThis.NyungaReference = ' + json.dumps(bank, separators=(',', ':')) + ';\n', encoding='utf-8')
print('Wrote', target.name, target.stat().st_size, 'bytes')
